version: '3.9'

services:
  billboard:
    image: trufflesuite/ganache-cli:v6.12.2
    ports:
      - 8545:8545
    volumes:
      - accounts:/accounts/
    command: ["--deterministic", "nerla","--gasLimit","0x6691b70", "--accounts", "1000", "--account_keys_path", "/accounts/accounts.json", "--debug"]
  enclave:
    image: ${APP_NAME}-enclave
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        SGX_MODE: SW
        SGX_DEBUG: 1
        APP_NAME: ${APP_NAME}
    depends_on:
      - billboard
    environment:
      SGX_MODE: SW
      PYTHONBREAKPOINT: ipdb.set_trace
      SGX_DEBUG: 1
      CCF_ENABLE: 0

      SGX_SPID: ${SGX_SPID}
      IAS_PRIMARY_KEY: ${IAS_PRIMARY_KEY}
      NUM_USERS: ${NUM_USERS}
      PROJECT_ROOT: /home/photon/${APP_NAME}

    volumes:
      - accounts:/usr/src/${APP_NAME}/accounts/
      - ../billboard:/home/photon/${APP_NAME}/billboard/
      - ../enclave:/home/photon/${APP_NAME}/enclave/
      - ../app:/home/photon/${APP_NAME}/app/
      - ../scripts:/home/photon/${APP_NAME}/scripts/
#      - ../applications/${APP_NAME}:/home/photon/${APP_NAME}/test_sgx

volumes:
  accounts: